const mongoose = require('mongoose');
const { Schema } = mongoose;

const realtorSchema = new Schema({
  user_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, // Link to the User model
  business_name: { type: String, required: false }, // Realtor's business name
  business_type: { type: String, required: true }, // Realtor's business type
  tax_id_image: { type: String, required: false }, // Realtor's tax ID
  verification_doc_image: { type: String, required: false }, // Realtor's verification document
  avg_rating: { type: Number, default: 0 }, // Average rating of the realtor
  is_subscribed: { type: Boolean, default: false }, // Subscription status (defaults to false)

  // Multiple Bank Details with Unique IDs
  bank_details: [
    new Schema(
      {
        _id: { type: Schema.Types.ObjectId, auto: true }, // Automatically generates a unique _id
        account_holder_name: { type: String, required: false }, // Name of the bank account holder
        bank_name: { type: String, required: false }, // Name of the bank
        account_number: { type: String, required: false }, // Bank account number
        branch_name: { type: String, required: false }, // Branch name (optional)
      },
      { _id: true } // Ensures each bank detail has an auto-generated ObjectId
    )
  ],

  total_revenue: { type: Number, default: 0 }, // Total revenue generated by the realtor
  available_revenue: { type: Number, default: 0 }, // Available revenue for the realtor

  created_at: { type: Date, default: Date.now }, // Timestamp of when the realtor record was created
  updated_at: { type: Date, default: Date.now }, // Timestamp of the last update
});

// Middleware to update 'updated_at' field on document update
realtorSchema.pre('save', function (next) {
  this.updated_at = Date.now();
  next();
});

const Realtor = mongoose.model('Realtor', realtorSchema);
module.exports = Realtor;
